// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test_newS.Models;

namespace test_newS.Migrations
{
    [DbContext(typeof(Model))]
    [Migration("20201223033326_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Domain.Flight.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ArrivalStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Domain.Transport.Transport", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.HasKey("FlightNumber");

                    b.HasIndex("FlightId");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("Domain.Transport.Transport", b =>
                {
                    b.HasOne("Domain.Flight.Flight", null)
                        .WithMany("Transport")
                        .HasForeignKey("FlightId");
                });

            modelBuilder.Entity("Domain.Flight.Flight", b =>
                {
                    b.Navigation("Transport");
                });
#pragma warning restore 612, 618
        }
    }
}
